### PR TITLE
Simulation

### PR DESCRIPTION
**Pull request by kingsoduah**

### CODE REVIEW

**Comment by joshuaunity** [comment]
Hi @Developer-Kings-dev i cant find your postman or insomnia collection in the repo.

**Comment by joshuaunity** [comment]
Hi @Developer-Kings-dev below is my review

1. when creating an account you shouldn't allow the user to put in an account number as that should be generated by the system instead
2. The dailylimit should also be set by the system
3. I shouldn't be allowed to create two accounts with the same details. like account number. Imagein your current bank account, now imagine there is someone out there with the same bank and account number. That shouldn't be so.
4. how does the delete API work? On your insomnia there was nothing parsed, should an ID be parsed in the URL or something? Which ever it is, update the collection 


besides form these,  think all the functionalities where implemented  correctly, just these fixes and some other opetinal improvements

**Comment by joshuaunity** [comment]
Hi @Developer-Kings-dev,

I have completed the review of your changes, and everything has been resolved. Great job! Your work qualifies you to receive the certificate of completion for this backend program.

As you move forward into the real world, I encourage you to pay close attention to details while continuing to enhance your technical skills. Keep up the good work!

Best regards,

**Comment by kingsoduah** [comment]
Thank you Sir for your efforts in making sure that your students gets the best knowledge to implement on real world projects.

**Pull request merged**
